title: I'm Bunlong.
description: > # this means to ignore newlines until "baseurl:"
  Bunlong is a DEV from Cambodia. He shares JavaScript, HTML, and CSS code tidbits on Twitter Facebook LinkedIn.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bunlong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bunlong # add your name
author-img: bunlong.jpg # add your photo
about-author: Follow me on <a>Twitter</a> to catch my weekly articles. # add description
social-twitter: bunlongvan # add your Twitter handle
social-facebook: CoderVlog # add your Facebook handle
social-github: bunlong # add your Github handle
social-linkedin: bunlongvan # add your Linkedin handle
social-email: bunlong.van@gmail.com # add your Email address

# Disqus
discus-identifier: bunlong # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
